; Баранчук Д.А. 114 
; " Зачёт с оценкой "

	INCLUDE IO1.ASM
STACK	SEGMENT STACK
	DB 128 DUP (?)
STACK	ENDS
DATA SEGMENT 
 Z1 DB 'Введите число: $'
 Z2 DB 'Неуд $'
 Z3 DB 'Удовл $'
 Z4 DB 'Хорошо $'
 Z5 DB 'Отлично $'
 Z6 DB 'Плохое число $'
 Z DW Z1
 Y DW Z6
 ADR DW Z2,Z3,Z4,Z5
DATA ENDS
CODE	SEGMENT
	ASSUME SS:STACK, DS:DATA, CS:CODE
BEGIN: 
 	MOV AX,DATA
	MOV DS,AX	
	MOV BX,0
	MOV DX,Z
	OUTSTR
	ININT BX
	CMP BX,5 ;IF AX>5 THEN GOTO BAD
	JA BAD
	CMP BX,2 ;IF AX<2 THEN GOTO BAD
	JB BAD	
	SUB BL,2
	ADD BL,BL
	MOV DX,0
	MOV DX,ADR[BX]
	OUTSTR
	NEWLINE
	FINISH
BAD:MOV DX,Y
    OUTSTR	
    NEWLINE
	FINISH
CODE	ENDS
	 END BEGIN
	 END BEGIN